# Generated by Django 4.2.1 on 2023-05-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('dni', models.IntegerField(max_length=15)),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_mod', models.DateField(auto_now=True)),
                ('fecha_nac', models.DateField()),
                ('direccion', models.CharField(max_length=60)),
                ('ciudad', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(max_length=20)),
                ('usuario', models.CharField(max_length=15)),
                ('contraseña', models.CharField(max_length=15)),
                ('rol_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('idpublicacion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=250)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('fecha_mod', models.DateField(auto_now=True)),
                ('cantidad', models.IntegerField(max_length=4)),
                ('preferencias', models.CharField(max_length=60)),
            ],
        ),
    ]
