# Generated by Django 4.2.1 on 2023-05-18 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='cantidad',
        ),
    ]
