# Generated by Django 4.2.1 on 2023-05-19 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer_app', '0002_remove_persona_dni_remove_persona_telefono_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
