# Generated by Django 4.2.1 on 2023-05-20 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer_app', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='suscripcion',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='publicante',
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
        migrations.DeleteModel(
            name='Suscripcion',
        ),
    ]
