# Generated by Django 4.2.1 on 2023-05-20 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('primer_app', '0005_remove_persona_suscripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=60)),
                ('apellidos', models.CharField(max_length=60)),
                ('dni', models.IntegerField()),
                ('fecha_alta', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('direccion', models.CharField(max_length=60)),
                ('ciudad', models.CharField(max_length=60)),
                ('provincia', models.CharField(max_length=60)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField()),
                ('usuario', models.CharField(max_length=15)),
                ('contraseña', models.CharField(max_length=15)),
                ('rol_admin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id_suscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField()),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=250)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('cantidad', models.IntegerField()),
                ('foto', models.ImageField(upload_to='')),
                ('preferencias_de_trueque', models.CharField(max_length=60)),
                ('categoria', models.CharField(choices=[('VEHI', 'Vehiculos'), ('ELEC', 'Electrodomesticos'), ('COME', 'Comestibles'), ('HOGA', 'Hogar'), ('JUGU', 'Juegos y Juguetes')], max_length=4)),
                ('publicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_app.persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='suscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='primer_app.suscripcion'),
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField(max_length=250)),
                ('fecha_creacion', models.DateField(auto_now=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('publicacion_comentada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_app.publicacion')),
                ('usuario_comentante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_app.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='primer_app.persona')),
                ('suscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='primer_app.suscripcion')),
            ],
        ),
    ]
