# Generated by Django 4.2.1 on 2023-05-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primer_app', '0007_alter_persona_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
