# Generated by Django 4.2.1 on 2023-05-20 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primer_app', '0010_suscripcion_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='publicacion',
            options={'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='suscripcion',
            options={'verbose_name_plural': 'Suscripciones'},
        ),
    ]
